version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/harmonyboard"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "placeholderapi"
      - dependency-name: "bungeecord-api"